#!/usr/bin/env python3
"""D7-B verifier — summary dashboard is wired to REAL article data + Telegram links map.

Runs fully offline (no network, DB writes, secrets, or send). It proves two things the
D7-B blocker required:

Part B — real article data:
  · docs/daily/dashboard-latest.html is generated by build_static_dashboard.py (builder
    reuses the preview template, reads no secrets/network).
  · The published dashboard's article rows come from the SAME shared brief object that
    docs/daily/latest.html uses (build_executive_brief.build_brief_via_mock_pipeline) —
    titles/sources are real, not the template's hardcoded demo sample.
  · Article cards carry data-lens + 내부 기사 reader + 보조 원문 사이트 links
    (target=_blank rel=noopener noreferrer), and the empty state still exists.
  · latest.html stays the full Executive Daily Brief; dashboard-latest.html stays the
    summary dashboard; the two remain separate.

Part A — Telegram button mapping is impossible to get wrong:
  · '대시보드 보기' → .../daily/dashboard-latest.html and '상세 리포트 보기' →
    .../daily/latest.html across swapped / duplicated / missing env configs, with the
    correct button order. The pre-send guard blocks non-canonical targets.
"""

import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUILDER = ROOT / "scripts" / "build_static_dashboard.py"
BRIEF_BUILDER = ROOT / "scripts" / "build_executive_brief.py"
SENDER = ROOT / "scripts" / "send_telegram.py"
TEMPLATE = ROOT / "templates" / "dashboard_preview.html"
DASHBOARD = ROOT / "docs" / "daily" / "dashboard-latest.html"
LATEST = ROOT / "docs" / "daily" / "latest.html"

SUMMARY_LABEL = "대시보드 보기"
FULL_REPORT_LABEL = "상세 리포트 보기"
BASE = "https://guides.playground-aidesignlab.co.kr/HDEC-News-Sensor/daily"
DASH_URL = f"{BASE}/dashboard-latest.html"
REPORT_URL = f"{BASE}/latest.html"
TOKEN_SHAPE = re.compile(r"[0-9]{8,}:[A-Za-z0-9_-]{20,}")

_failures = []


def check(name: str, ok: bool, detail: str = "") -> bool:
    tag = "PASS" if ok else "FAIL"
    line = f"[{tag}] {name}"
    if detail:
        line += f" — {detail}"
    print(line)
    if not ok:
        _failures.append(name)
    return ok


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


def _model(html: str) -> dict:
    m = re.search(r'<script type="application/json" id="preview-model">(.*?)</script>',
                  html, re.S)
    if not m:
        return {}
    try:
        return json.loads(m.group(1))
    except ValueError:
        return {}


def _clean_env(**extra: str) -> dict:
    env = {**os.environ, "APP_MODE": "mock"}
    for key in ("NEWS_MODE", "MACRO_MODE", "REPORT_URL", "DASHBOARD_URL",
                "TELEGRAM_BOT_TOKEN", "TELEGRAM_CHAT_IDS", "TELEGRAM_SEND_MODE",
                "REVIEW_APPROVED", "CONFIRM_SEND", "MESSAGE", "TELEGRAM_BOT_USERNAME"):
        env.pop(key, None)
    env.update(extra)
    return env


def _run(args, env=None, timeout=300) -> subprocess.CompletedProcess:
    return subprocess.run(args, cwd=ROOT, capture_output=True, text=True,
                          env=env or _clean_env(), timeout=timeout)


# ---------------------------------------------------------------------------
# 1 · 빌더가 실기사 데이터를 주입한다 (시크릿/네트워크 0건)
# ---------------------------------------------------------------------------

def check_builder() -> None:
    src = _read(BUILDER)
    check("1a: build_static_dashboard.py 존재", bool(src))
    check("1b: 빌더가 preview template을 재사용",
          '"templates" / "dashboard_preview.html"' in src)
    check("1c: 빌더가 공유 brief 파이프라인을 사용(실기사 동일 출처)",
          "build_brief_via_mock_pipeline" in src)
    check("1d: 빌더 소스가 env/secrets를 직접 읽지 않음",
          "os.environ" not in src and "TELEGRAM_" not in src)
    check("1e: 빌더 소스가 네트워크 라이브러리를 import하지 않음",
          not re.search(r"^\s*(import|from)\s+(urllib|requests|httpx|socket)\b", src, re.M))

    proc = _run([sys.executable, str(BUILDER), "--json"])
    if not check("1f: builder --json 동작", proc.returncode == 0, (proc.stderr or "")[-200:]):
        return
    meta = json.loads(proc.stdout)
    check("1g: 빌더가 실기사 사용 플래그(uses_real_articles)",
          meta.get("uses_real_articles") is True)
    check("1h: 실 news 행 다수(>=6) + featured 제목 존재",
          (meta.get("news_row_count") or 0) >= 6 and bool(meta.get("featured_title")),
          f"news={meta.get('news_row_count')} featured={meta.get('featured_title')!r}")
    check("1i: 정직성 라벨 유지(데모/체결값/미연동)",
          meta.get("has_data_honesty_labels") is True)


# ---------------------------------------------------------------------------
# 2 · 대시보드 기사 = latest.html과 같은 brief 출처 (실데이터, 데모 표본 아님)
# ---------------------------------------------------------------------------

def _brief_titles() -> set:
    proc = _run([sys.executable, str(BRIEF_BUILDER), "--json"])
    if proc.returncode != 0:
        return set()
    brief = json.loads(proc.stdout)
    titles = set()
    for key in ("top_immediate_signals", "top_new_issues", "hdec_direct_signals",
                "ai_radar_signals", "business_signals", "risk_regulation_signals",
                "competitor_supply_signals", "macro_economy_signals"):
        for s in brief.get(key) or []:
            if s.get("title"):
                titles.add(s["title"])
    return titles


def check_real_provenance() -> None:
    brief_titles = _brief_titles()
    if not check("2a: 공유 brief에서 신호 제목 수집(>0)", bool(brief_titles),
                 f"{len(brief_titles)}건"):
        return
    with tempfile.TemporaryDirectory(prefix="hdec_real_") as tmp:
        out = Path(tmp) / "dash.html"
        proc = _run([sys.executable, str(BUILDER), "--output", str(out)])
        if not check("2b: builder --output 동작", proc.returncode == 0 and out.exists(),
                     (proc.stderr or "")[-200:]):
            return
        model = _model(out.read_text(encoding="utf-8"))
        rows = model.get("news_rows") or []
        ai = model.get("ai_rows") or []
        row_titles = [r.get("title") for r in rows + ai if r.get("title")]
        # 모든 대시보드 기사 제목이 brief 신호 제목에 존재 → 동일 출처(실데이터) 증명
        missing = [t for t in row_titles if t not in brief_titles]
        check("2c: 대시보드 기사 제목이 모두 공유 brief에 존재(동일 출처)",
              row_titles and not missing,
              f"브리프 밖 제목: {missing[:2]}" if missing else f"{len(row_titles)}건 일치")
        # 템플릿의 하드코딩 데모 표본과 다름 (데모만 쓰지 않음)
        tpl_rows = _model(_read(TEMPLATE)).get("news_rows") or []
        check("2d: 대시보드 news_rows가 템플릿 데모 표본과 다름 (데모만 아님)",
              rows != tpl_rows and bool(rows))
        check("2e: 대시보드 기사 행이 실 URL(http) 보유",
              all(str(r.get("url", "")).startswith("http") for r in rows) and bool(rows))


# ---------------------------------------------------------------------------
# 3 · 커밋된 대시보드: 실기사 구조 + 렌즈 태그 + 링크 + 빈 상태 + 정직성
# ---------------------------------------------------------------------------

VALID_LENS = {
    "now", "new", "ai", "civil_infrastructure", "building_housing", "plant",
    "new_energy", "development_business", "global_business", "safety_quality",
    "hyundai_group", "competitor_contractors", "trust_companies", "developers",
    "oil_energy", "hormuz", "domestic_site", "overseas_site", "overseas_branch",
    "overseas_subsidiary",
}


def check_committed_dashboard() -> None:
    if not check("3a: docs/daily/dashboard-latest.html 존재", DASHBOARD.exists()):
        return
    html = _read(DASHBOARD)
    check("3b: 빌더 export 마커 포함", "dashboard-export:summary" in html)
    check("3c: 보이지 않는 news-data-mode 마커 포함",
          bool(re.search(r"news-data-mode:(live|mock)", html)))
    model = _model(html)
    rows = model.get("news_rows") or []
    ai = model.get("ai_rows") or []
    check("3d: 커밋 대시보드가 실 news 행 보유(>=6)", len(rows) >= 6, f"{len(rows)}행")
    check("3e: 모든 기사 행에 비어있지 않은 lens 태그", bool(rows) and all(r.get("lens") for r in rows))
    keys = {l for r in rows + ai for l in r.get("lens", [])}
    check("3f: 모든 lens 키가 유효한 nav 필터 키",
          keys <= VALID_LENS, f"미정의: {sorted(keys - VALID_LENS)}")
    check("3g: featured 카드 data-lens + data-category(실데이터)",
          bool(re.search(r'class="card featured"[^>]*data-lens="[^"]+"[^>]*data-category="[^"]+"', html)))
    check("3h: 빈 상태 요소 유지(newsEmpty/aiEmpty)",
          'id="newsEmpty"' in html and 'id="aiEmpty"' in html)
    for lab in ("데모 데이터", "현재 체결값 아님", "미연동"):
        check(f"3i: 정직성 라벨 유지 '{lab}'", lab in html)
    check("3j: 발송 토큰/시크릿 미혼입",
          not TOKEN_SHAPE.search(html) and "TELEGRAM_BOT_TOKEN" not in html)


# ---------------------------------------------------------------------------
# 4 · 내부 reader 기본 CTA + 안전한 보조 원문 링크 또는 부재 안내
# ---------------------------------------------------------------------------

def check_article_links() -> None:
    html = _read(DASHBOARD)
    model = _model(html)
    rows = model.get("news_rows") or []
    with_url = [r for r in rows if str(r.get("url", "")).startswith("http")]

    safe_external_links = re.findall(
        r'<a[^>]+href=["\']https?://[^"\']+["\'][^>]+target="_blank"[^>]+rel="noopener noreferrer"',
        html,
        re.I,
    )
    bad_external_hrefs = re.findall(
        r'href=["\']https?://[^"\']*(?:hdec\.kr/warning|WARNING\.jpg|example\.com/mock-|example\.com|example\.invalid)[^"\']*["\']',
        html,
        re.I,
    )

    check("4a: 실기사 행이 url을 보유(>=1)", bool(with_url), f"{len(with_url)}/{len(rows)}")
    check("4b: 원문 링크는 있으면 안전 속성, 없으면 mock/example/warning href 0건",
          bool(safe_external_links) or not bad_external_hrefs,
          f"safe={len(safe_external_links)} bad={len(bad_external_hrefs)}")

    template = _read(ROOT / "templates" / "dashboard_preview.html")
    check("4c: 기본 CTA는 기사 보기 내부 reader",
          "function openArticleReader" in template
          and ">기사 보기</button>" in template)
    check("4d: 원문 사이트는 접근상태가 붙은 보조 링크",
          "원문 사이트 ↗" in template and "access-badge" in template)
    check("4e: 링크 부재 시 mock/example/warning 외부 href를 만들지 않음",
          not bad_external_hrefs,
          f"bad={len(bad_external_hrefs)}")


# ---------------------------------------------------------------------------
# 5 · latest.html=전체 리포트 / dashboard-latest.html=요약 대시보드 분리 유지
# ---------------------------------------------------------------------------

def check_separation() -> None:
    if not check("5a: docs/daily/latest.html 존재", LATEST.exists()):
        return
    latest = _read(LATEST)
    dashboard = _read(DASHBOARD)
    check("5b: latest.html은 전체 Executive Daily Brief", "Executive Daily Brief" in latest)
    check("5c: latest.html != dashboard-latest.html", latest != dashboard)
    for tok in ('id="preview-model"', "dashboard-export:summary",
                "function applyLens", 'data-filter="all"'):
        check(f"5d: 전체 리포트에 대시보드 전용 토큰 '{tok}' 미혼입", tok not in latest)


# ---------------------------------------------------------------------------
# 6 · Telegram 버튼 매핑 (요약→dashboard-latest, 전체→latest) — 오설정 자가교정
# ---------------------------------------------------------------------------

def _targets(report_url: str = None, dashboard_url: str = None) -> tuple[str, str]:
    """send_telegram.resolve_button_targets()를 주어진 env로 호출 → (summary, report)."""
    saved = {k: os.environ.get(k) for k in ("REPORT_URL", "DASHBOARD_URL")}
    try:
        for k, v in (("REPORT_URL", report_url), ("DASHBOARD_URL", dashboard_url)):
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v
        return st.resolve_button_targets()
    finally:
        for k, v in saved.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v


def check_telegram_mapping() -> None:
    sys.path.insert(0, str(ROOT / "scripts"))
    global st
    try:
        import send_telegram as st
    except Exception as exc:  # noqa: BLE001
        check("6: send_telegram import", False, str(exc))
        return

    # 6a — build_payload 라벨/순서/URL 매핑 (직접 인자)
    payload = st.build_payload("DRY", "m", REPORT_URL, "", DASH_URL)
    btns = json.loads(payload["reply_markup"])["inline_keyboard"][0]
    labels = [b["text"] for b in btns]
    urls = [b["url"] for b in btns]
    check("6a: 버튼 순서 = 요약 대시보드 → 전체 리포트",
          labels[:2] == [SUMMARY_LABEL, FULL_REPORT_LABEL], " / ".join(labels[:2]))
    check("6b: 요약→dashboard-latest, 전체→latest 매핑",
          urls[:2] == [DASH_URL, REPORT_URL])

    # 6c~6f — 정식/뒤바뀜/중복 env 모두 정식 타겟으로 정규화 (오설정 자가교정)
    cases = {
        "정상": (REPORT_URL, DASH_URL),
        "뒤바뀜": (DASH_URL, REPORT_URL),          # REPORT_URL=dashboard, DASHBOARD_URL=report
        "둘다 latest": (REPORT_URL, REPORT_URL),
        "둘다 dashboard": (DASH_URL, DASH_URL),
        "DASHBOARD 누락": (REPORT_URL, None),
    }
    for name, (rep, dash) in cases.items():
        summary, report = _targets(rep, dash)
        good = (summary.endswith("/daily/dashboard-latest.html")
                and report.endswith("/daily/latest.html"))
        check(f"6c: env[{name}] → 요약=dashboard-latest · 전체=latest (자가교정)",
              good, f"summary={summary[-40:]} report={report[-30:]}")

    # 6g — 종류 식별 불가 커스텀 URL은 잘못된 타겟으로 표기되고 발송 차단 사유가 된다
    summary, report = _targets("https://x.example/p.html", "https://x.example/p.html")
    errors = st.button_target_errors(summary, report)
    check("6d: 비정식 커스텀 URL은 button_target_errors가 잡아냄(발송 차단)", bool(errors),
          f"{len(errors)} errors")

    # 6h — 발송 경로에 발송 직전 타겟 검증 가드 + preflight 모드 존재
    sender_src = _read(SENDER)
    check("6e: send 경로에 발송 직전 버튼 타겟 가드 존재",
          "button_target_errors(dashboard_url, report_url)" in sender_src)
    check("6f: --preflight 모드 존재(워크플로 발송 전 검증)",
          '"--preflight"' in sender_src and "def preflight_links" in sender_src)

    # 6i — 워크플로가 각 send step 전에 --preflight를 같은 env로 돌린다
    workflow = _read(ROOT / ".github" / "workflows" / "telegram-notify.yml")
    check("6g: 워크플로가 send 전에 --preflight 실행",
          "send_telegram.py --preflight" in workflow
          and workflow.count("send_telegram.py --preflight") >= 1)


def main() -> int:
    print(f"== verify_dashboard_real_data @ {ROOT} ==")
    check_builder()
    check_real_provenance()
    check_committed_dashboard()
    check_article_links()
    check_separation()
    check_telegram_mapping()

    print()
    if _failures:
        print(f"RESULT: FAIL ({len(_failures)} 항목)")
        for f in _failures:
            print(f"  - {f}")
        return 1
    print("RESULT: PASS — 요약 대시보드 실기사 연동 + Telegram 링크 매핑 확인 (D7-B)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
