#!/usr/bin/env python3
"""D7-Q verifier — live dashboard rows always carry semantic lens tags (no empty, no fake).

Runs fully offline (no network, DB writes, secrets, or send). It guards the scheduled
live-refresh repeat-stability blocker: a live dashboard generated by the workflow must
never emit an article row with an empty lens tag. The fix is semantic, so this checks
BOTH halves of the contract:

  1. Relevant rows get meaningful, valid lens tags (apartment/AI-robot → building_housing
     + ai; roads/ports/rail → civil_infrastructure; EPC/plant → plant; …).
  2. Irrelevant rows with no executive/construction relevance (consumer new-product
     blurbs, generic non-construction AI) are EXCLUDED from dashboard rows — not
     fake-labeled to satisfy a non-empty check.

Part A — committed dashboard preview-model integrity (docs/daily/dashboard-latest.html):
  · news_rows / ai_rows: every emitted row has a non-empty lens.
  · lens_banks: every banked row has a non-empty lens.
  · every emitted lens key is a valid dashboard nav/filter key.

Part B — regression guards for the exact failure examples (conditional / absence-based,
so they hold for any live snapshot):
  · the Gatorade/Lotte Chilsung consumer-product row never appears in dashboard rows.
  · the AI parking-robot apartment row, IF present, carries building_housing AND ai.

Part C — synthetic row-normalizer unit checks (call the builder's lens logic directly,
deterministic regardless of mock/live data):
  · irrelevant consumer product  → no lens → excluded.
  · AI parking robot apartment   → lens includes building_housing AND ai.
  · generic residential article  → conservative construction lens (building_housing), not empty.
  · pure non-construction AI      → not tagged ai (gate prevents over-tagging) → excluded.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import build_static_dashboard as bsd  # noqa: E402  (offline import — no network at load)

DASHBOARD = ROOT / "docs" / "daily" / "dashboard-latest.html"

# Verifier-local copy so drift between verifier and builder is itself a failure (C5).
VALID_LENS = {
    "now", "new", "ai", "civil_infrastructure", "building_housing", "plant",
    "new_energy", "development_business", "global_business", "safety_quality",
    "hyundai_group", "competitor_contractors", "trust_companies", "developers",
    "oil_energy", "hormuz", "domestic_site", "overseas_site", "overseas_branch",
    "overseas_subsidiary",
}

# Exact failure examples from the scheduled-run blocker.
GATORADE_TITLE = "[오늘의신상]물만 부으면 게토레이…롯데칠성, 분말형 제품 출시"
ROBOT_TITLE = "디에이치·에피트 아파트에 'AI 주차로봇' 도입"
# Substrings that identify the irrelevant consumer row regardless of headline rewording.
CONSUMER_MARKERS = ("게토레이", "롯데칠성")

_failures = []


def check(name: str, ok: bool, detail: str = "") -> bool:
    line = f"[{'PASS' if ok else 'FAIL'}] {name}"
    if detail:
        line += f" — {detail}"
    print(line)
    if not ok:
        _failures.append(name)
    return ok


def _row_lens(row: dict) -> list:
    lenses = row.get("lens") or row.get("lenses") or row.get("lens_keys") or []
    if isinstance(lenses, str):
        return [lenses] if lenses.strip() else []
    return list(lenses or [])


def _row_ctx(bucket: str, i: int, row: dict) -> str:
    prov = row.get("provenance") or {}
    return (f"[{bucket}][{i}] title={row.get('title')!r} source={row.get('source')!r} "
            f"category={prov.get('category')!r} radar_section={prov.get('radar_section')!r} "
            f"executive_section={prov.get('executive_section')!r} lens={_row_lens(row)}")


def _load_model() -> dict | None:
    if not check("A0: docs/daily/dashboard-latest.html 존재", DASHBOARD.exists()):
        return None
    html = DASHBOARD.read_text(encoding="utf-8", errors="ignore")
    m = re.search(r'<script type="application/json" id="preview-model">\s*(.*?)\s*</script>',
                  html, re.S)
    if not check("A0b: preview-model JSON 추출", bool(m)):
        return None
    try:
        return json.loads(m.group(1))
    except json.JSONDecodeError as exc:
        check("A0b: preview-model JSON 파싱", False, str(exc))
        return None


def _banked_rows(model: dict):
    for lens, rows in (model.get("lens_banks") or {}).items():
        for i, row in enumerate(rows or []):
            yield f"lens_banks:{lens}", i, row


def check_committed_model(model: dict) -> None:
    # A1/A2: 노출 행(news_rows/ai_rows)에 빈 렌즈 0건.
    empty_rows = []
    emitted = set()
    for bucket in ("news_rows", "ai_rows"):
        for i, row in enumerate(model.get(bucket) or []):
            lens = _row_lens(row)
            emitted.update(lens)
            if not lens:
                empty_rows.append(_row_ctx(bucket, i, row))
    check("A1: news_rows/ai_rows 모든 행에 비어있지 않은 lens",
          not empty_rows, "; ".join(empty_rows))

    # A3: 렌즈 뱅크에 빈 렌즈 행 0건.
    empty_banked = []
    for bucket, i, row in _banked_rows(model):
        lens = _row_lens(row)
        emitted.update(lens)
        if not lens:
            empty_banked.append(_row_ctx(bucket, i, row))
    check("A3: lens_banks 모든 행에 비어있지 않은 lens",
          not empty_banked, "; ".join(empty_banked))

    # A4: 모든 emitted 렌즈 키가 유효 nav 키.
    invalid = sorted(emitted - VALID_LENS)
    check("A4: 모든 emitted lens 키가 유효 nav/filter 키", not invalid, f"미정의: {invalid}")


def check_regressions(model: dict) -> None:
    # B1: 무관 소비재 행(게토레이/롯데칠성)이 어떤 대시보드 버킷에도 없음.
    hits = []
    rows = list(enumerate(model.get("news_rows") or []))
    rows += [(i, r) for i, r in enumerate(model.get("ai_rows") or [])]
    bank_rows = [(f"{b}#{i}", r) for b, i, r in _banked_rows(model)]
    everywhere = [("news/ai", i, r) for i, r in rows] + [("bank", b, r) for b, r in bank_rows]
    for where, idx, r in everywhere:
        t = r.get("title") or ""
        if any(mk in t for mk in CONSUMER_MARKERS):
            hits.append(f"{where}#{idx}: {t!r}")
    check("B1: 무관 소비재 행이 대시보드 행/뱅크에 미노출", not hits, "; ".join(hits))

    # B2: AI 주차로봇 행이 존재하면 building_housing + ai 를 반드시 보유(조건부).
    robot_bad = []
    robot_seen = 0
    for where, idx, r in everywhere:
        t = r.get("title") or ""
        if "AI 주차로봇" in t or ("에피트" in t and "아파트" in t):
            robot_seen += 1
            lens = set(_row_lens(r))
            if not {"building_housing", "ai"} <= lens:
                robot_bad.append(f"{where}#{idx}: lens={sorted(lens)}")
    check(f"B2: AI 주차로봇 행은 building_housing+ai 보유 (관측 {robot_seen}건)",
          not robot_bad, "; ".join(robot_bad))


def _syn(title: str, category: str = "hdec", section: str = "business_overseas") -> dict:
    return {"title": title, "category": category, "radar_section": section,
            "category_label": "", "source": "", "url": "http://example.com/x"}


def check_synthetic() -> None:
    # C5: 검증기 VALID_LENS == 빌더 VALID_LENS (드리프트 방지).
    check("C5: VALID_LENS 가 빌더와 동일", VALID_LENS == set(bsd.VALID_LENS),
          f"diff={sorted(VALID_LENS ^ set(bsd.VALID_LENS))}")

    # C1: 무관 소비재 → 렌즈 없음 → 제외.
    consumer = _syn(GATORADE_TITLE)
    c1 = bsd._lens_for(consumer)
    check("C1: 무관 소비재 신호 → 렌즈 없음(대시보드 제외)",
          c1 == [] and not bsd._has_dashboard_lens(consumer), f"lens={c1}")

    # C2: AI 주차로봇 아파트 → building_housing + ai.
    robot = _syn(ROBOT_TITLE)
    c2 = set(bsd._lens_for(robot))
    check("C2: AI 주차로봇 아파트 → building_housing + ai 태깅",
          {"building_housing", "ai"} <= c2 and bsd._has_dashboard_lens(robot),
          f"lens={sorted(c2)}")

    # C3: 정밀 렌즈가 전혀 없는 주거 기사 → 보수적 폴백으로 building_housing(빈 렌즈 방지).
    resi = _syn("강남 아파트 입주 시작")
    c3 = set(bsd._lens_for(resi))
    check("C3: 정밀렌즈 없는 주거 기사 → 폴백 building_housing(빈 렌즈 방지)",
          c3 == {"building_housing"} and bsd._has_dashboard_lens(resi), f"lens={sorted(c3)}")

    # C4: 비건설 순수 AI → ai 미태깅(과태깅 방지) → 제외.
    pure_ai = _syn("삼성전자, AI 반도체 신제품 공개")
    c4 = set(bsd._lens_for(pure_ai))
    check("C4: 비건설 순수 AI → ai 미태깅 + 콘텐츠 렌즈 없음(제외)",
          "ai" not in c4 and not bsd._has_dashboard_lens(pure_ai), f"lens={sorted(c4)}")

    # C6: 이미 정밀 렌즈가 있는 기사는 주거어가 있어도 building_housing 폴백을 받지 않는다
    # (과태깅 방지 · displayable 인플레이션 회피) — 예: "아파트·원전…"은 원전→plant.
    precise = _syn("아파트·원전에 AI 인프라까지…발주 깨어나는 건설株")
    c6 = set(bsd._lens_for(precise))
    check("C6: 정밀렌즈 보유 기사는 building_housing 폴백 비적용(plant 유지)",
          "plant" in c6 and "building_housing" not in c6, f"lens={sorted(c6)}")


def main() -> int:
    print(f"== verify_dashboard_lens_integrity @ {ROOT} ==")
    model = _load_model()
    if model is not None:
        check_committed_model(model)
        check_regressions(model)
    check_synthetic()

    print()
    if _failures:
        print(f"RESULT: FAIL ({len(_failures)} 항목)")
        for f in _failures:
            print(f"  - {f}")
        return 1
    print("RESULT: PASS — 대시보드 행 lens 무결성 + 의미 기반 제외/태깅 확인 (D7-Q)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
